license = "ARR"

issueTrackerURL="https://github.com/Kishku7/mod_support/issues"
[[mods]]
    modId = "m1"
    version = "${mod_version}"
    displayName = "M1 - Machine One AI Interface"
    authors = "Kishku7"
    description = '''Exposes the real Minecraft client through a localhost text channel for local automation/AI control.'''

[[dependencies.m1]]
    modId = "neoforge"
    type = "required"
    versionRange = "${neoforgeRange}"
    ordering = "NONE"
    side="BOTH"
[[dependencies.m1]]
    modId = "minecraft"
    type = "required"
    versionRange = "${mcRange}"
    ordering = "NONE"
    side="BOTH"
