package com.kishku7.m1;

import net.minecraft.client.Minecraft;
import net.minecraft.client.gui.screens.Screen;
import net.minecraft.world.entity.EntityType;
import com.mojang.blaze3d.pipeline.RenderTarget;
//[[[cog
//import sys; sys.path.insert(0, codegen); import compat
//for imp in compat.m1compat_imports(mcver): cog.outl("import " + imp + ";")
//]]]
//[[[end]]]

/**
 * Cross-version drift bridges for M1. Generated by Cog from _codegen/compat.py, driven by the build
 * cell's MC version (-D mcver=...). Emits DIRECT access per version -- which resolves on BOTH the
 * intermediary runtime (pre-26 Fabric; Loom remaps mojmap->intermediary) and the mojmap runtime
 * (MC 26+, NeoForge, Forge/FG6 1.20.1+), unlike reflection-by-mojmap-name (which misses on intermediary).
 * Fall-through rule: facade -> Cog -> segregated; this is the Cog layer.
 */
public final class M1Compat {
    private M1Compat() {}

    // pre-26.2: Minecraft.screen (field). 26.2+: Minecraft.gui.screen().
    public static Screen screen(Minecraft mc) {
        //[[[cog
        //for ln in compat.screen_get(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    // pre-26.2: Minecraft.setScreen(Screen). 26.2+: Minecraft.gui.setScreen(Screen).
    public static void setScreen(Minecraft mc, Screen screen) {
        //[[[cog
        //for ln in compat.screen_set(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    // pre-26.2: Minecraft.getMainRenderTarget(). 26.2+: Minecraft.gameRenderer.mainRenderTarget().
    public static RenderTarget mainRenderTarget(Minecraft mc) {
        //[[[cog
        //for ln in compat.render_target(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    // pre-26.2: EntityType.ZOMBIE (field). 26.2+: BuiltInRegistries.ENTITY_TYPE.getValue(EntityTypeIds.ZOMBIE).
    public static EntityType<?> zombie() {
        //[[[cog
        //for ln in compat.zombie(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }
}
