package com.kishku7.m1;

import net.minecraft.client.Minecraft;
import net.minecraft.world.item.crafting.Ingredient;

import java.util.List;

//[[[cog
//import sys; sys.path.insert(0, codegen); import compat
//]]]
//[[[end]]]

/**
 * Cog twin of RecipeCompat -- direct per-version recipe-book access for pre-26 Fabric (intermediary
 * runtime, where the reflection twin misses). 1.21.2+ casts the opaque handle to RecipeDisplayEntry;
 * pre-1.21.2 to RecipeHolder. Generated by Cog from _codegen/compat.py. Keep the surface identical to
 * the reflection twin at shared_minecraft/.../RecipeCompat.java. All version-specific types are fully
 * qualified so no version-gated imports are needed.
 */
public final class RecipeCompat {
    private RecipeCompat() {}

    public static List<Object> entries(Minecraft mc) {
        //[[[cog
        //for ln in compat.rc_entries(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static String resultId(Minecraft mc, Object entry) {
        //[[[cog
        //for ln in compat.rc_result_id(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static boolean canCraft(Minecraft mc, Object entry) {
        //[[[cog
        //for ln in compat.rc_can_craft(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static List<Ingredient> requirements(Object entry) {
        //[[[cog
        //for ln in compat.rc_requirements(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static List<String> ingredientItemIds(Ingredient ing) {
        //[[[cog
        //for ln in compat.rc_ingredient_ids(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static void placeRecipe(Minecraft mc, int containerId, Object entry, boolean shift) {
        //[[[cog
        //for ln in compat.rc_place(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }

    public static String label(Object entry) {
        //[[[cog
        //for ln in compat.rc_label(mcver): cog.outl(ln)
        //]]]
        //[[[end]]]
    }
}
